version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_ricky_and_morthy
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: ricky_and_morthy
            MYSQL_PASSWORD: rootpw
            MYSQL_USER: user
        networks:
            - ricky_and_morthy

    # nginx pour rendre mon application       
    nginx:
        image: nginx:1.23.3-alpine
        restart: on-failure
        volumes:
            - './:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8089:80'
        depends_on:
            - php
        networks:
            - ricky_and_morthy

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
        networks:
            - ricky_and_morthy

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8088:80
        environment:
            PMA_HOST: db
        networks:
            - ricky_and_morthy

networks:
    ricky_and_morthy:


volumes:
    db-data:
